### ISSUE TITLE
some paths from Ubuntu 18.04, maybe use them on build

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/ansible-role-compile-samba#11]
generated by `smbd -b`
```
Paths:
   SBINDIR: /usr/sbin
   BINDIR: /usr/bin
   CONFIGFILE: /etc/samba/smb.conf
   LOGFILEBASE: /var/log/samba
   LMHOSTSFILE: /etc/samba/lmhosts
   LIBDIR: /usr/lib/x86_64-linux-gnu
   MODULESDIR: /usr/lib/x86_64-linux-gnu/samba
   SHLIBEXT: so
   LOCKDIR: /var/run/samba
   STATEDIR: /var/lib/samba
   CACHEDIR: /var/cache/samba
   PIDDIR: /var/run/samba
   SMB_PASSWD_FILE: /etc/samba/smbpasswd
   PRIVATE_DIR: /var/lib/samba/private
```
